# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# plugins

plugins:          [jekyll-paginate]

# Setup
title:            If You Find The Earth Boring...
tagline:          
description:      'A Boring Website'
url:              http://ifyoufindtheearthboring.com
# baseurl:          /

author:
  name:           'Sun Ra'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jrherr/boring
