# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            If You Find The Earth Boring...
tagline:          
description:      'A Boring Website'
url:              http://ifyoufindtheearthboring.com
baseurl:             ''
paginate:            5
permalink:           pretty

author:
  name:           'Sun Ra'
  url:            # https://twitter.com/
  email:          ''

# Gems
plugins:
  - jekyll-paginate
  - github-pages

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
github:
  repo:           https://github.com/jrherr/boring


